### ISSUE TITLE
RuntimeError: Acquire on closed pool

### ISSUE THREAD

**Issue by ionelmc** [celery/celery#1839]
```
[2014-01-31 23:15:13,294: WARNING/Worker-353] +++ Stresstest suite end (repetition 1) +++
[2014-01-31 23:19:53,971: WARNING/Worker-353] +++ Stresstest suite start (repetition 1) +++
[2014-01-31 23:19:53,973: WARNING/Worker-342] --- 1: manyshort(0/50) rep#1 runtime: 0 seconds/0 seconds  ---
[2014-01-31 23:19:53,974: WARNING/Worker-342] /home/ionel/projects/celery/celery/app/trace.py:343: RuntimeWarning: Exception raised outside body: RuntimeError('Acquire on closed pool',):
Traceback (most recent call last):
  File "/home/ionel/projects/celery/celery/app/trace.py", line 262, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/ionel/projects/celery/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/home/ionel/projects/kombu/kombu/connection.py", line 881, in acquire
    R = self.prepare(R)
  File "/home/ionel/projects/kombu/kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "/home/ionel/projects/kombu/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/home/ionel/projects/kombu/kombu/connection.py", line 872, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: {'exc_message': 'Acquire on closed pool', 'exc_type': 'RuntimeError'}

  exc, exc_info.traceback)))
[2014-01-31 23:19:53,975: CRITICAL/MainProcess] Task stress.app._marker[b1838c4d-04f8-492c-b472-917e5db29fd8] INTERNAL ERROR: {'exc_message': 'Acquire on closed pool', 'exc_type': 'RuntimeError'}
Traceback (most recent call last):
  File "/home/ionel/projects/celery/celery/app/trace.py", line 262, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/home/ionel/projects/celery/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/home/ionel/projects/kombu/kombu/connection.py", line 881, in acquire
    R = self.prepare(R)
  File "/home/ionel/projects/kombu/kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "/home/ionel/projects/kombu/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/home/ionel/projects/kombu/kombu/connection.py", line 872, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: {'exc_message': 'Acquire on closed pool', 'exc_type': 'RuntimeError'}
```

**Comment by chenwardT** [comment]
I just started getting this problem today.

    [2015-06-29 18:02:58,103: ERROR/MainProcess] Task riot_api.wrapper.get_matches_from_ids[d01746a4-f039-4347-a498-df7653dd0689] raised unexpected: RuntimeError('Acquire on closed pool',)
    Traceback (most recent call last):
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/home/chen/python-projects/lol_stats2/lol_stats2/riot_api/wrapper.py", line 141, in get_matches_from_ids
        RiotAPI.get_match(match['matchId'], region=region, include_timeline=False)
      File "/home/chen/python-projects/lol_stats2/lol_stats2/riot_api/wrapper.py", line 105, in get_match
    link=store_get_match.s())
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/celery/app/task.py", line 559, in apply_async
        **dict(self._get_exec_options(), **options)
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/celery/app/base.py", line 347, in send_task
        with self.producer_or_acquire(producer) as P:
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/celery/utils/objects.py", line 79, in __enter__
        ).__enter__()
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/connection.py", line 868, in acquire
        R = self.prepare(R)
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/pools.py", line 61, in prepare
        p = p()
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/utils/functional.py", line 29, in __call__
        return self.evaluate()
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/utils/functional.py", line 32, in evaluate
        return self._fun(*self._args, **self._kwargs)
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/pools.py", line 41, in create_producer
        conn = self._acquire_connection()
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/pools.py", line 38, in _acquire_connection
        return self.connections.acquire(block=True)
      File "/home/chen/.virtualenvs/lol_stats2_dev/lib/python3.4/site-packages/kombu/connection.py", line 859, in acquire
        raise RuntimeError('Acquire on closed pool')
    RuntimeError: Acquire on closed pool

My machine's log in /var/log/rabbitmq is showing several of the following entries:

    =ERROR REPORT==== 29-Jun-2015::18:01:08 ===
    AMQP connection <0.11051.0> (closing), channel 1 - error:
    {amqp_error,channel_error,"expected 'channel.open'",'channel.close'}

and

    =WARNING REPORT==== 29-Jun-2015::18:01:07 ===
    closing AMQP connection <0.11033.0> (127.0.0.1:35672 -> 127.0.0.1:5672):
    connection_closed_abruptly

The rest are the usual INFO level reports for accepting connections.

Using the following (relevant) packages:
amqp==1.4.6
billiard==3.3.0.20
celery==3.1.18
kombu==3.0.26

I recently started using RabbitMQ/celery (and most of what it is dependent on) so please let me know what else would be useful to list; just following the lead of others here.

**Comment by thedrow** [comment]
Looks like we need to reopen.

**Comment by ask** [comment]
What result backend are you using?

I'm not able to reproduce here using the rpc result backend..

Please also try to upgrade to the latest 3.1 version

**Comment by chenwardT** [comment]
It has been a bit since I touched the code, but based on my commit history, it looks like I had disabled the results backend at the time; no "backend" argument is passed to Celery():

https://github.com/chenwardT/lol_stats2/commit/0dd4fa895fc30869ca40d814d39e976e4cec6eb2

Will report back w/results of using latest version when I get a chance.

**Comment by edanayal** [comment]
I'm experiencing this issue too with latest celery 3.1.19.
I'm trying to build and send simple code for reproducing the issue, but without success so far...
Here's a description of my system:
I have few queues and few workers with different concurrency (2, 1, 5, ...). Backend is rabbit too.
special config I'm using: -Ofair
Various tasks are injected by celerybeat every minute or so, sometimes few tasks together.
Tasks are mostly long duration but CPU is very low, as the tasks are waiting for external actions to complete (like DB queries...)
Some of the tasks wait for other task groups in other queues to complete (I know it's not good practice, but I inherited the code as is...)
Any idea?

**Comment by ask** [comment]
Please include the traceback!

**Comment by edanayal** [comment]
Sorry, here it is:

/usr/lib/python2.6/site-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: RuntimeError('Acquire on closed pool',):
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "/usr/lib/python2.6/site-packages/celery/backends/base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/lib/python2.6/site-packages/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 61, in prepare
    p = p()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 29, in __call__
    return self.evaluate()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 32, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 41, in create_producer
    conn = self._acquire_connection()
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool

Thank you!

**Comment by edanayal** [comment]
Still happens in latest version 3.1.20... :-(

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/lib/python2.6/site-packages/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 61, in prepare
    p = p()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 29, in __call__
    return self.evaluate()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 32, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 41, in create_producer
    conn = self._acquire_connection()
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')

In other workers, after this initial exception, the exception might be the same or a bit different:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/lib/python2.6/site-packages/celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "/usr/lib/python2.6/site-packages/celery/backends/base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/lib/python2.6/site-packages/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 61, in prepare
    p = p()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 29, in __call__
    return self.evaluate()
  File "/usr/lib/python2.6/site-packages/kombu/utils/functional.py", line 32, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 41, in create_producer
    conn = self._acquire_connection()
  File "/usr/lib/python2.6/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/lib/python2.6/site-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')

Thank you

**Comment by pthornton** [comment]
This issue is occurring daily for me now.  Rebooting seems to fix it temporarily.  
billiard 3.3.0.21
kombu 3.0.29

Traceback (most recent call last):
  File "/home/pthornton/ares/vem/com/circ/ares/vsphere/impl/tasks.py", line 166, in start_environment
    (mipk, step, None), countdown=10)
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/celery/app/task.py", line 560, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/celery/app/base.py", line 348, in send_task
    with self.producer_or_acquire(producer) as P:
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/celery/utils/objects.py", line 78, in __enter__
    *self.fb_args, **self.fb_kwargs
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/home/pthornton/ares/venv/lib/python2.7/site-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool

**Comment by ask** [comment]
Please include some more information, e.g. what broker, result backend, command-line arguments used to start the worker, and worker related configuration.

Even better would be a set of steps required to reproduce, as I have yet to see the issue happen in stress testing.

**Comment by pthornton** [comment]
Django application.
Using supervisor project to start celery worker:
[program:celery-worker]
command={{ PYTHON }} {{ PROJECT_DIR }}/manage.py celery worker -linfo -E -A com.circ.vem --concurrency=20
amqp://guest:**@127.0.0.1:5672//
rabbitmq-server-3.3.5-4.el7.noarch

Seems to be related to volume.  Starting from a reboot it can take hours to reproduce, then happens repeatedly.  This is running the same set of steps that work successfully earlier in the day.

**Comment by pthornton** [comment]
app.conf.update(
    CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend',
    CELERY_TIMEZONE='UTC'   # set timezone in here
)
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

**Comment by Rajlaxmi** [comment]
Hi,

I am facing similar errors.
```
[[2016-03-27 12:48:18,987: INFO/MainProcess] Received task: workerProg.exec_func[734a9822-8ca6-44f9-99fa-ab7d5b8526b4]
[2016-03-27 12:48:18,988: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x1bb9578> (args:('workerProg.exec_func', '734a9822-8ca6-44f9-99fa-ab7d5b8526b4', .... ; kwargs:{})
[2016-03-27 12:48:18,989: DEBUG/MainProcess] Task accepted: workerProg.exec_func[734a9822-8ca6-44f9-99fa-ab7d5b8526b4] pid:31076
[2016-03-27 12:48:21,187: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2016-03-27 12:48:25,277: CRITICAL/MainProcess] Task workerProg.exec_func[734a9822-8ca6-44f9-99fa-ab7d5b8526b4] INTERNAL ERROR: RuntimeError('Acquire on closed pool',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.6/site-packages/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/usr/local/lib/python2.6/site-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/usr/local/lib/python2.6/site-packages/kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "/usr/local/lib/python2.6/site-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/local/lib/python2.6/site-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
```

This is my config file:

```
import sys
import os
sys.path.append(os.getcwd())

CELERYD_CONCURRENCY = 25

#Disable prefecting
CELERYD_PREFETCH_MULTIPLIER = 1

#Enable retrying of lost or failed tasks
CELERY_ACKS_LATE = True

# default RabbitMQ broker
BROKER_URL = 'amqp://...'

# default RabbitMQ backend
CELERY_RESULT_BACKEND = 'amqp'

#Delete a message in queue after given minutes
CELERY_EVENT_QUEUE_TTL = 20*60

#Delete temporary error queues
CELERY_STORE_ERRORS_EVEN_IF_IGNORED = False

#Expiry Time in secs of Celery Result Task Queue
CELERY_TASK_RESULT_EXPIRES=10*60

#kill worker executing task more than given seconds and replace with a new one
CELERYD_TASK_TIME_LIMIT=60*60

CELERY_QUEUES = {"autoscalegroup": {"exchange": "autoscalegroup", "routing_key": "autoscalegroup"}}
```

I run into this error every 5-6 days and I have to restart the processes again.

**Comment by pthornton** [comment]
This issue is keeping me from going live.  I can provide webex access to look at this issue and can repeat it regularly.  Just saw it scroll past in the logs now.

**Comment by edanayal** [comment]
If it's an option, you may try changing the broker+backend from RabbitMQ to Redis.
So far works fine for me (2 weeks already)

**Comment by Rajlaxmi** [comment]
After receiving this error, my workers get restarted. However, they do not accept any new tasks. Logs shows that heartbeat messages are received but tasks are not accepted.

Some part of log:

```
Restarting celery worker (/usr/local/bin/celery worker -A proj -l info --config=celeryconfig.py -Ofair)
[2016-04-02 03:19:07,788: ERROR/MainProcess] Process 'Worker-350' pid:32804 exited with 'exitcode 70'
..
..

 -------------- celery@.. v3.1.19 (Cipater)
---- **** -----
--- * ***  * -- Linux-...
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x16a9f50
- ** ---------- .> transport:   amqp://mainClient:**@... : .../vhostClient
- ** ---------- .> results:     amqp
- *** --- * --- .> concurrency: 25 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> autoscalegroup   exchange=autoscalegroup(direct) key=autoscalegroup


[tasks]
  . workerProg.exec_func

[2016-04-02 03:19:09,129: WARNING/MainProcess] /usr/local/lib/python2.6/site-packages/celery/apps/worker.py:161: CDeprecationWarning:

[2016-04-02 03:19:09,179: INFO/MainProcess] Connected to amqp://mainClient:**@52.91.139.132:5672/vhostClient
[2016-04-02 03:19:09,193: INFO/MainProcess] mingle: searching for neighbors
[2016-04-02 03:19:10,208: INFO/MainProcess] mingle: sync with 4 nodes
[2016-04-02 03:19:10,208: INFO/MainProcess] mingle: sync complete
[2016-04-02 03:19:10,248: WARNING/MainProcess] celery@ip-10-0-1-46 ready.
[2016-04-02 03:19:11,188: INFO/MainProcess] Events of group {task} enabled by remote.
[2016-04-02 04:03:36,346: INFO/MainProcess] sync with celery@ip-10-0-1-107
[2016-04-02 04:03:36,577: INFO/MainProcess] sync with celery@ip-10-0-1-87

```

**Comment by pthornton** [comment]
> If it's an option, you may try changing the broker+backend from RabbitMQ to Redis.
So far works fine for me (2 weeks already)

Unfortunately, did not help.  I'm still seeing the same issue using Redis.  Happened within 5 minutes.

**Comment by spicyramen** [comment]
I see similar problem:
Machine is Ubuntu 14.04 2GB RAM Digita
Celery:
/usr/local/bin/celery worker -n celeryd@%h -f /usr/local/src/xxxxx/application/xxxxx/log/celeryd.log --loglevel=DEBUG --autoscale=50,10

amqp==1.4.6
flower==0.8.4
celery==3.1.18
kombu==3.0.26

[2016-04-21 11:46:56,517: INFO/Worker-1171] deploy_uc() Valid Server. Discovery was successful
[2016-04-21 11:46:56,554: INFO/Worker-1171] deploy_uc() Job: XXXXXXX is in progress
[2016-04-21 11:46:56,587: CRITICAL/MainProcess] Task catalogue.cisco.uc.deploy_uc.imbue_uc[939B9C5407] INTERNAL ERROR: RuntimeError('Acquire on closed pool',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "/usr/lib/python2.7/dist-packages/celery/backends/base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "/usr/lib/python2.7/dist-packages/celery/backends/amqp.py", line 124, in store_result
    with self.app.amqp.producer_pool.acquire(block=True) as producer:
  File "/usr/lib/python2.7/dist-packages/kombu/connection.py", line 868, in acquire
    R = self.prepare(R)
  File "/usr/lib/python2.7/dist-packages/kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "/usr/lib/python2.7/dist-packages/kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "/usr/lib/python2.7/dist-packages/kombu/connection.py", line 859, in acquire
    raise RuntimeError('Acquire on closed pool')
RuntimeError: Acquire on closed pool
[2016-04-21 12:37:46,338: DEBUG/MainProcess] | Worker: Closing Hub...

**Comment by ask** [comment]
I'm working in the dark here, as I have yet to reproduce the issue.  The patch above may or may not fix the issue, but this is the place in the code where the pool is closed after fork.

Either the problem is in that code, or alternatively something is keeping a reference to the pool and is that way unaffected by the after fork handling code.

Hopefully knowing where to start debugging, could help you finding the source of the problem

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

**Comment by chrisspen** [comment]
I'm also experiencing this with Celery 4.1 with a RabbitMQ backend.

**Comment by thedrow** [comment]
@chrisspen Can you please open a new issue with the necessary details to debug this problem?

**Comment by prasadsidda** [comment]
Traceback (most recent call last): File "/home/ubuntu/django8/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task R = retval = fun(args, kwargs) File "/home/ubuntu/django8/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__ return self.run(args, *kwargs) File "/home/ubuntu/integra/integra/sunrise/core/config/utils.py", line 59, in inner return func(args,kwargs) File "/home/ubuntu/integra/integra/sunrise/core/config/schedule.py", line 147, in inner return func(args,kwargs) File "/home/ubuntu/integra/integra/sunrise/core/config/schedule.py", line 301, in inner return func(args,kwargs) File "/home/ubuntu/integra/integra/sunrise/cashbook/bookvalues/fileimport.py", line 523, in importfiledata delete_temp_table(task_request_id,True) File "/home/ubuntu/integra/integra/sunrise/core/config/utils.py", line 199, in delete_temp_table **running_tasks = i.active()** File "/home/ubuntu/django8/local/lib/python2.7/site-packages/celery/app/control.py", line 94, in active return self._request('active') File "/home/ubuntu/django8/local/lib/python2.7/site-packages/celery/app/control.py", line 81, in _request timeout=self.timeout, reply=True, File "/home/ubuntu/django8/local/lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast limit, callback, channel=channel, File "/home/ubuntu/django8/local/lib/python2.7/site-packages/kombu/pidbox.py", line 315, in _broadcast serializer=serializer) File "/home/ubuntu/django8/local/lib/python2.7/site-packages/kombu/pidbox.py", line 285, in _publish with self.producer_or_acquire(producer, chan) as producer: File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__ return self.gen.next() File "/home/ubuntu/django8/local/lib/python2.7/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire with self.producer_pool.acquire() as producer: File "/home/ubuntu/django8/local/lib/python2.7/site-packages/kombu/resource.py", line 74, in acquire raise RuntimeError('Acquire on closed pool') RuntimeError: Acquire on closed pool

**Comment by prasadsidda** [comment]
def delete_temp_table(request_id,old=False):
    cursor = connection.cursor()
    cursor.execute("DROP TABLE IF EXISTS temp_worker_table_"+request_id)
    if old:
        cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name LIKE 'temp_worker_table_%'")
        tables_list = [table[0] for table in cursor.fetchall()]
        if len(tables_list):
            i = inspect()
            **running_tasks = i.active()**
            if running_tasks is not None:
                active_tasks = ["temp_worker_table_"+item['id'] for cleary_task in running_tasks.values() for item in cleary_task]
                tables_list = set(tables_list) - set(active_tasks)
                if len(tables_list):
                    sql_deltab = ';'.join(["DROP TABLE IF EXISTS "+table for table in tables_list])+';'
                    cursor.execute(sql_deltab)
    cursor.close()

**Comment by chrisspen** [comment]
@thedrow I fixed this by implementing my own base task that calls Django's `close_old_connections()`. e.g.

    import celery

    from django.db import close_old_connections

    class BaseTask(celery.Task):

        def __call__(self, *args, **kwargs):
            # Necessary to prevent OperationalError: (2006, 'MySQL server has gone away') caused by old connections not being cleaned up.
            close_old_connections()
            return super(BaseTask, self).__call__(*args, **kwargs)

    @task(base=BaseTask)
    def mytask():
        blah

**Comment by jheld** [comment]
I am also having this issue w/redis as backend and broker, using json.

```
Traceback (most recent call last):
  File "/Users/jasonheld/PycharmProjects/circulationAPI/circulation/reliability_map.py", line 267, in get_reliability_map
    found_num = sum(num_proc_on_worker(w) for w in workers_on_queue(u'reliability_{}'.format(carrier)))
  File "/Users/jasonheld/PycharmProjects/circulationAPI/circulation/reliability_map.py", line 267, in <genexpr>
    found_num = sum(num_proc_on_worker(w) for w in workers_on_queue(u'reliability_{}'.format(carrier)))
  File "/.../tasks.py", line 80, in workers_on_queue
    for k, v in six.viewitems(celery_app.control.inspect().active_queues()):
  File "/.../lib/python2.7/site-packages/celery/app/control.py", line 116, in active_queues
    return self._request('active_queues')
  File "/.../lib/python2.7/site-packages/celery/app/control.py", line 81, in _request
    timeout=self.timeout, reply=True,
  File "/.../lib/python2.7/site-packages/celery/app/control.py", line 436, in broadcast
    limit, callback, channel=channel,
  File "/.../lib/python2.7/site-packages/kombu/pidbox.py", line 315, in _broadcast
    serializer=serializer)
  File "/.../lib/python2.7/site-packages/kombu/pidbox.py", line 285, in _publish
    with self.producer_or_acquire(producer, chan) as producer:
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/.../lib/python2.7/site-packages/kombu/pidbox.py", line 247, in producer_or_acquire
    with self.producer_pool.acquire() as producer:
  File "/.../lib/python2.7/site-packages/kombu/resource.py", line 74, in acquire
    raise RuntimeError('Acquire on closed pool')
```

This only happens when we're using the `control` module. Sometimes it works okay.

This code path was even in a retry-loop, so in the end it still failed to execute.

python2.7, redis, django 1.11, celery 4.0.2.

**Comment by maznu** [comment]
Plenty of this happening on our systems running Celery==3.1.18 and kombu==3.0.37 with RabbitMQ 3.6.15. Doesn't happen every time - just retried and job and it was fine. Sometimes restarting RabbitMQ fixes things, but it's hard to tell whether this actually fixes things or whether it's just probability.

Traceback out of Sentry looks something like:

``` text
kombu/connection.py in acquire at line 874
        :raises LimitExceeded: if block is false
          and the limit has been exceeded.
        """
        if self._closed:
            raise RuntimeError('Acquire on closed pool')
        if self.limit:
            while 1:
                try:
                    R = self._resource.get(block=block, timeout=timeout)
                except Empty:
kombu/pools.py in _acquire_connection at line 38
kombu/pools.py in prepare at line 63
kombu/connection.py in acquire at line 883
celery/backends/amqp.py in store_result at line 124
celery/app/trace.py in trace_task at line 283
```

**Comment by auvipy** [comment]
that version is no longer supported. please update to 4.2 series

**Comment by auvipy** [comment]
continue discussion in #4410
