### ISSUE TITLE
CELERY_RESULT_SERIALIZER = 'json' breaks Exception marshaling

### ISSUE THREAD

**Issue by xtfxme** [celery/celery#2518]
Setting `CELERY_RESULT_SERIALIZER = json` and raising an exception in the worker leads to this:

```
/path/to/lib/python2.7/site-packages/celery/result.py in get(self, timeout, propagate, interval, no_ack, follow_parents, EXCEPTION_STATES, PROPAGATE_STATES)
    173             status = meta['status']
    174             if status in PROPAGATE_STATES and propagate:
--> 175                 raise meta['result']
    176             return meta['result']
    177     wait = get  # deprecated alias to :meth:`get`.

TypeError: exceptions must be old-style classes or derived from BaseException, not dict
```

where the contents of `meta['result']` are (in my case):

```
{u'exc_message': u'unknown keys: nam', u'exc_type': u'ValueError'}
```

so it *looks* like celery could convert the dict to a real exception before raising, but it does not currently.  Changing back to `pickle` works as expected.

bug can be reproduced with the following:

```python
# jsonresults.py
from celery.app.base import Celery

CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'amqp'

app = Celery(config_source=__name__)

@app.task
def hello():
    raise ValueError('go away')
```

worker:

```
# python -m celery --app=jsonresults:app worker
```

caller:

```python
import jsonresults
jsonresults.hello.delay().get()
```

**Comment by allardhoeve** [comment]
This is biting me as well. Any news?

**Comment by xtfxme** [comment]
I came to post my workaround, but your patch looks much more simple/solid/proper.

For posterity, we just installed an alternative JSON serializer that special cased Exceptions:

```python
from kombu import serialization


def serialization_register_json():
    """Register a encoder/decoder for JSON serialization."""
    from anyjson import loads as json_loads, dumps as json_dumps
    import exceptions

    def _loads(obj):
        if isinstance(obj, serialization.bytes_t):
            obj = obj.decode()
        obj = json_loads(obj)
        if obj.get('traceback') is not None:
            try:
                exc_type = obj['result']['exc_type']
                exc_message = obj['result']['exc_message']
            except KeyError:
                pass
            else:
                exc_type = getattr(exceptions, exc_type)
                obj['result'] = exc_type(exc_message)
        return obj

    serialization.registry.register('json', json_dumps, _loads,
                      content_type='application/json',
                      content_encoding='utf-8')

# install our alternative JSON serializer
serialization_register_json()
```

but it only works for builtin exceptions... hopefully your patch covers raising arbitrary exceptions? I'll be able to try it out myself soon.

**Comment by allardhoeve** [comment]
It does arbitrary exceptions, but not well. As you can see in the test, the
name of the exception is the same as the original but not the exact type.
So if you do:

```python
try:
    result.get()  # raises ValueError
except ValueError as e:
    # got e
    pass
```

Then that will NOT catch the exception, the type of the new exception is
`celery.exceptions.base.ValueError` or so.

But at least with this patch there is no more TypeError.

It will probably prove hard if not impossible to reraise arbitrary
exceptions well because the receiver might be lacking or differing in code
implementations of the thrown exception. Also, the exception info might not
have been serialized to JSON, think of CalledProcessErrors that have an
errno attribute that is not serialized.

This should be fixed in a patch to the function that serializes and
deserializes exceptions, not here.

**Comment by cerisier** [comment]
@xtfxme workaround works great in Python 2.x but not in Python 3.x as exceptions module doesn't exist anymore.

While waiting for 3.2.0 to be released. Here is my workaround for Python 3 using celery own exception recreation system.

```
from celery.utils.serialization import create_exception_cls

from kombu import serialization
from kombu.utils.encoding import from_utf8

def serialization_register_json():
    """Register a encoder/decoder for JSON serialization."""
    from anyjson import loads as json_loads, dumps as json_dumps

    def _loads(obj):
        if isinstance(obj, serialization.bytes_t):
            obj = obj.decode()
        obj = json_loads(obj)
        if obj.get('traceback') is not None:
            try:
                exc_type = obj['result']['exc_type']
                exc_message = obj['result']['exc_message']
            except KeyError:
                pass
            else:
                obj['result'] = create_exception_cls(
                    from_utf8(exc_type), __name__)(exc_message)
        return obj

    serialization.registry.register('json', json_dumps, _loads,
                      content_type='application/json',
                      content_encoding='utf-8')

# install our alternative JSON serializer
serialization_register_json()
```

**Comment by naggie** [comment]
(Moving comment from PR to main issue)

I think this is still an issue -- using the latest dev snapshot and celery 3.1.19 I get the same problem with AMPQ/RabbitMQ and JSON. Redis is fine. Sqlite is not.

**Comment by ask** [comment]
Do you have a traceback, because it works fine for me in master?

**Comment by brianleipprandt** [comment]
Looks like this commit was not part of the tag v3.1.20
$ git branch --contains 33e72fdbc7b07fc26d13bcdc36fb6f42c8291b66
  master
$ git tag --contains 33e72fdbc7b07fc26d13bcdc36fb6f42c8291b66
# No results

Can we get this added to the next 3.1.x release?

**Comment by ask** [comment]
@brianleipprandt Thanks! cherry-picked into 3.1 branch
