### ISSUE TITLE
add_periodic_task will overwrite existing tasks if only kwargs differ between two

### ISSUE THREAD

**Issue by underyx** [celery/celery#2834]
Haven't had time to actually test this, so I'm really sorry if I turn out to be wrong, but I just stumbled upon these two lines: https://github.com/celery/celery/blob/1a953d6aa2d25c4a7b84a133c1560b45e168b539/celery/app/base.py#L577-L578

It seems to me that if I wanted to schedule `add.s(a=1, b=1)` and `add.s(a=2, b=2)`, both would be saved with the `add:` key, so both couldn't exist at the same time in the config.

This issue gets worse with the fact that canvassing tasks use kwargs too, so for instance all `chain` tasks would be saved to `celery.chain:`.

But then again, I might be completely wrong here, so sorry again if that turns out to be the case!

**Comment by ask** [comment]
Thanks!  I fixed this now, but names can be very long if you have chains etc, so you probably would want to specify names explicitly some times.

**Comment by underyx** [comment]
@ask thanks for the fix!

Regarding chains; they don't work anyway, or at least when I tried to schedule some, this line kept raising in the worker: https://github.com/celery/celery/blob/a7c168d6df82bcd060e02e647a916d61627959dc/celery/app/builtins.py#L181

**Comment by aimestereo** [comment]
thanks for the fix of the original bug, but I've faced the second bug mentioned by @underyx `chain is not a real task` when trying to schedule chain with celerybeat. I couldn't find any issue for that, so I suppose it's still not fixed, @ask do you know about this issue?

P.S. we are still on `v4.1.0`
