### ISSUE TITLE
Celery does not respect exceptions types when using a serializer different than pickle.

### ISSUE THREAD

**Issue by jcsaaddupuy** [celery/celery#3586]
## Checklist
```
~ : celery -A analystick report
software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.2
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379/1
```

## Steps to reproduce
(See example code below)

## Expected behavior

__When using a result serializer different than pickle__, exceptions types should be the same as the raised exception.

## Actual behavior
Celery does not respect the exception type but create _a new type_ instead.

The main problem is that instead of using the actual type of the exception, celery will [reconstruct a type](https://github.com/celery/celery/blob/0f87321df385c5f3dca717ec2a4a9c0d25f88054/celery/utils/serialization.py#L43-L45) on the fly, but without respecting the original exception module.

For example, using the `yaml` result serializer (I believe it will be the same for `json`): 
- if a task raises a `ValueError`, the caller will receive a `celery.backends.base.ValueError`
- if a task raises a `custom.module.CustomError`, the caller will receive a `celery.backends.base.CustomError`

This ends with wrongs behaviour when raising a exception from a task and trying to catch it from the caller.

### Minimal reproductible test
As an example, I've setup a minimal reproductible test, using a redis backend :

celery config (I can provide a full config if needed):
```python
CELERY_TASK_SERIALIZER = 'yaml'
CELERY_RESULT_SERIALIZER='yaml'
```

Tasks : 

```python
# module myapp.tasks
from myapp import celery_app
@celery_app.task
def raises_valueerror():
    raise ValueError('Builtin exception')

class CustomError(Exception):
    pass

@celery_app.task
def raises_customerror():
    raise CustomError('Custom exception', {'a':1})
```

Unittest : 
```python
from myapp import tasks
from myapp.tasks import CustomError

def test_builtin_exception():
    t = tasks.raises_valueerror.s()
    r = t.apply_async()

    exc = None
    try:
        r.get(propagate=True)
    except Exception as e:
        exc = e

    # with celery bug, the actual class of exc will be  `celery.backends.base.ValueError` instead of builtin ValueError
    assert isinstance(exc, ValueError), "Actual class %s}" % (exc.__class__)

def test_custom_exception():
    t = tasks.raises_customerror.s()
    r = t.apply_async()

    exc = None
    try:
        r.get(propagate=True)
    except Exception as e:
        exc = e

    # with celery bug, the actual class of exc will be  `celery.backends.base.CustomError` instead of builtin CustomError
    assert isinstance(exc, CustomError), "1/2 Actual class is %s" % (exc.__class__)
    assert isinstance(exc, tasks.CustomError), "2/2 Actual class is %s" % (exc.__class__)

```

Theses tests will fail with the following errors : 

```
# ...
AssertionError: Actual class <class 'celery.backends.base.ValueError'>
# ...
AssertionError: 1/2 Actual class is <class 'celery.backends.base.CustomError'>
```

Another side effect for this problem will be that a code like the one below won't work if a subtask raise a `ValueError`, as the propagated exception won't be of the builtin type `ValueError` but `celery.backends.base.ValueError`:

```python
try:
    r.get(propagate=True)
except ValueError as e:
    # do something        
```

This problem will be the same also for any custom exceptions.

While I'm not sure about the possible side-effects, [I have a fix for this](https://github.com/jcsaaddupuy/celery/commit/8d4e613e24f6561fdaafd4e6ede582ceac882804) and I will gladly create a PR for this problem as it seems pretty critical.

What do you think ?

**Comment by ask** [comment]
This is actually deliberate, as none of json, yaml or msgpack are able to reconstruct exceptions.

The alternative is to load exceptions of any type, which opens up for similar security issues as using pickle.

**Comment by estan** [comment]
If this is deliberate, perhaps this issue should be closed? Or are there any plans to try to make it work, despite the security implications?

**Comment by vladcalin** [comment]
Is this situation documented? I was not able to find anything regarding this behaviour in the documentation.

**Comment by georgepsarakis** [comment]
@vladcalin @estan please check https://github.com/celery/celery/pull/3592 . As you can see this is still on-going. Any feedback is appreciated!

**Comment by cscetbon** [comment]
Hey here, will this issue be fixed one day ? Should we stop using custom exception ? Is there any workaround for now ?

**Comment by auvipy** [comment]
please check this PR https://github.com/celery/celery/pull/5074

**Comment by cscetbon** [comment]
Thanks @auvipy. Looking at the other PR.

**Comment by auvipy** [comment]
@thedrow could you check this issue?

**Comment by thedrow** [comment]
@auvipy Why have we closed this issue? Is it resolved?

**Comment by auvipy** [comment]
I think it was mistakenly closed

**Comment by thedrow** [comment]
@auvipy #5074 fixed this, right?

**Comment by auvipy** [comment]
that PR was reverted so might not be fixed yet

**Comment by radekwlsk** [comment]
It is still a problem or at least was as of 17th March 2020.

Got this in my custom Exception which is used for task's `autoretry_for` list:
```python
        # TODO: call super().__init__(*args) once celery issue is fixed
        #  https://github.com/celery/celery/issues/3586
```

**Comment by auvipy** [comment]
wasn't this fixed by https://github.com/celery/celery/pull/4864 ?

**Comment by auvipy** [comment]
> It is still a problem or at least was as of 17th March 2020.
> 
> Got this in my custom Exception which is used for task's `autoretry_for` list:
> 
> ```python
>         # TODO: call super().__init__(*args) once celery issue is fixed
>         #  https://github.com/celery/celery/issues/3586
> ```

can you provide a test case to verify?

**Comment by radekwlsk** [comment]
@auvipy You have said yourself at the end of last year that
> that PR was reverted so might not be fixed yet

And now you are linking 2 years old MR that was supposed to fix it.

I will check on Monday if it still is a problem and report back with exact error if that is not the case.

Thank you for quick response!

**Comment by kmcentush** [comment]
@auvipy I am still seeing this issue on Celery v5.1.2. Is there a reason that https://github.com/celery/celery/pull/5074 was reverted and never revisited?

I'm not sure how I can work around this issue otherwise.
