### ISSUE TITLE
Custom queue: Consumer does not have any callbacks

### ISSUE THREAD

**Issue by aleperno** [celery/celery#3789]
Im upgrading a configuration from Celery 3.1.25 up to 4.0.2, currently I am seeing an issue when I start the worker and there's a message queued, it raises a 'NotImplementedError'. This doesn't happen when performed the other way around (first the worker and then send the message).

The error:
```
[2017-01-20 17:12:13,984: INFO/MainProcess] mingle: sync with 11 nodes
[2017-01-20 17:12:13,985: INFO/MainProcess] mingle: sync complete
[2017-01-20 17:12:13,993: INFO/MainProcess] Canceling queue celery
[2017-01-20 17:12:13,998: INFO/MainProcess] Started consuming from 1.my_queue
[2017-01-20 17:12:14,001: CRITICAL/MainProcess] Unrecoverable error: NotImplementedError(u'Consumer does not have any callbacks',)
Traceback (most recent call last):
  File "/opt/my-program/lib/python2.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/opt/my-program/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/my-program/lib/python2.7/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
  File "/opt/my-program/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/opt/my-program/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/my-program/lib/python2.7/site-packages/celery/worker/pidbox.py", line 50, in start
    self.node.channel = c.connection.channel()
  File "/opt/my-program/lib/python2.7/site-packages/kombu/connection.py", line 266, in channel
    chan = self.transport.create_channel(self.connection)
  File "/opt/my-program/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 100, in create_channel
    return connection.channel()
  File "/opt/my-program/lib/python2.7/site-packages/amqp/connection.py", line 456, in channel
    channel.open()
  File "/opt/my-program/lib/python2.7/site-packages/amqp/channel.py", line 448, in open
    spec.Channel.Open, 's', ('',), wait=spec.Channel.OpenOk,
  File "/opt/my-program/lib/python2.7/site-packages/amqp/abstract_channel.py", line 73, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/abstract_channel.py", line 93, in wait
    self.connection.drain_events(timeout=timeout)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/connection.py", line 469, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/method_framing.py", line 88, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/connection.py", line 473, in on_inbound_method
    method_sig, payload, content,
  File "/opt/my-program/lib/python2.7/site-packages/amqp/abstract_channel.py", line 142, in dispatch_method
    listener(*args)
  File "/opt/my-program/lib/python2.7/site-packages/amqp/channel.py", line 1613, in _on_basic_deliver
    fun(msg)
  File "/opt/my-program/lib/python2.7/site-packages/kombu/messaging.py", line 623, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/opt/my-program/lib/python2.7/site-packages/kombu/messaging.py", line 588, in receive
    raise NotImplementedError('Consumer does not have any callbacks')
NotImplementedError: Consumer does not have any callbacks
```

The definition of the queue:
```python
some_id = 1

class SetQueue(bootsteps.StartStopStep):
    requires = ('celery.worker.consumer:Tasks', )

    def __init__(self, parent, **kwargs):
        self.my_queue = kwargs.get('my_queue')

    def start(self, parent):
        if self.my_queue:
            parent.cancel_task_queue(app.conf.CELERY_DEFAULT_QUEUE)
            parent.add_task_queue('{}.{}'.format(some_id, self.my_queue))

class SetHostname(bootsteps.StartStopStep):
    def __init__(self, parent, **kwargs):
        self.my_queue = kwargs.get('my_queue')
        parent.hostname = '{}@{}'.format(self.my_queue, some_id)

def my_custom_queue(parser):
    parser.add_argument(
        '--my-queue', help='Task queue base name.', type=str
    )

app.user_options['worker'].add(my_custom_queue)
app.steps['worker'].add(SetHostname)
app.steps['consumer'].add(SetQueue)
```
I'm having trouble finding what I'm missing.

Something I found in the [whats new](http://docs.celeryproject.org/en/latest/whatsnew-4.0.html) doc is the following
`The worker no longer has a Queues bootsteps, as it is now superfluous.`
and think may be related but dont know what it means.

Thanks in advance for any help

**Comment by aleperno** [comment]
### Update

Trying to further debug this issue I've found the error occurs only when it consumes from a remote queue.
This is when we consume from remote

```
[2017-02-24 16:45:02,059: INFO/MainProcess] Connected to amqp://<user>:**@<remote_ip>:5672//
[2017-02-24 16:45:02,079: INFO/MainProcess] mingle: searching for neighbors
[2017-02-24 16:45:03,156: INFO/MainProcess] mingle: sync with 10 nodes
[2017-02-24 16:45:03,156: INFO/MainProcess] mingle: sync complete
[2017-02-24 16:45:03,176: INFO/MainProcess] Canceling queue celery
[2017-02-24 16:45:03,184: INFO/MainProcess] Started consuming from 1.my_queue
[2017-02-24 16:45:03,192: CRITICAL/MainProcess] Unrecoverable error: NotImplementedError(u'Consumer does not have any callbacks',)
```
This is when we consume from local
```
[2017-02-24 17:31:35,597: INFO/MainProcess] Connected to amqp://<user>:**@localhost:5672//
[2017-02-24 17:31:35,607: INFO/MainProcess] mingle: searching for neighbors
[2017-02-24 17:31:36,623: INFO/MainProcess] mingle: sync with 1 nodes
[2017-02-24 17:31:36,623: INFO/MainProcess] mingle: sync complete
[2017-02-24 17:31:36,626: INFO/MainProcess] Canceling queue celery
[2017-02-24 17:31:36,628: INFO/MainProcess] Started consuming from 1.my_queue
[2017-02-24 17:31:36,634: INFO/MainProcess] my_queue@1 ready.
[2017-02-24 17:31:36,638: INFO/MainProcess] Received task: <a_task>[4a25a5d2-933d-4111-9dca-b99187ffa757]  ETA:[2017-02-24 20:31:27.514538+00:00]
```
There's no difference on how I run the consumer worker. It only differs the queue location.

**Comment by aleperno** [comment]
Sorry to bump this issue, but has anyone any hint of why is this happening?

Thanks

**Comment by auvipy** [comment]
could you verify the issue on top of master?

**Comment by aleperno** [comment]
I will definitely try to check this issue on master and update this issue. Thanks

**Comment by auvipy** [comment]
this might probably been fixed in master. report if not

**Comment by OultimoCoder** [comment]
This bug exists using celery 4.4.2.

Utilising a bootstep that calls add_task_queue will fail if you have pending messages in the queue. Failure is called when consumer.task_consumer.consume() is called in add_task_queue.

**Comment by OultimoCoder** [comment]
```
class AgentQueueConsumption(StartStopStep):
    requires = {'celery.worker.consumer.tasks:Tasks'}
    name = 'Agent Queue Consumption'

    @staticmethod
    def _get_queue_names(model):
        return [workflow.queue_name for workflow in model.objects.all()]

    def _get_all_queue_names(self):
        from common.django.apps.workflows.models.query_document import Workflow as Qd_Workflow
        from common.django.apps.index_document.models import Workflow as Id_Workflow

        return self._get_queue_names(Qd_Workflow) + self._get_queue_names(Id_Workflow)

    @requires_django('agent.settings')
    def start(self, parent):
        """
        Retrieve all active queues from the database and start consuming from them.
        """
        from .control import add_task_queue

        queue_names = self._get_all_queue_names()
        for queue_name in queue_names:
            add_task_queue(parent, queue_name)


app = load(main='agent', set_as_current=True)
app.steps['consumer'].update({AgentQueueConsumption})
```

This will fail with the error:
```
    raise NotImplementedError('Consumer does not have any callbacks')
NotImplementedError: Consumer does not have any callbacks
```

To get around this you can implement the logic you need from add_task_queue without calling consume and on start the agent will be consuming from the queues:

```
queue = consumer.app.amqp.queues.select_add(queue_name)
if not consumer.task_consumer.consuming_from(queue):
    consumer.task_consumer.add_queue(queue)
```

**Comment by Diggsey** [comment]
@auvipy can you re-open this issue, it still occurs in 5.0.0
