### ISSUE TITLE
Subscribe too much celery-task-meta using Redis backend

### ISSUE THREAD

**Issue by memwey** [celery/celery#3808]
celery:4.0.2 python:3.5.2 redis:2.10.5 celery-with-redis:3.0.0
os:CentOS release 6.7 (Final) 64bit

With redis as backend, using `redis-cli monitor` command, when adding a task into celery, it actually uses the `SUBSCRIBE` command in redis. Like `"SUBSCRIBE" "celery-task-meta-cb1792d7-9e9d-43d9-b374-3a8b15c97790"`

In my code, it's something like this

```
a.py
def main():
    while True:
        call_celery()

def call_celery():
    chord((task_a.s(), task_b.s()), task_c.s())()
```

However, I found a strange thing that after adding an amount of tasks, redis will sometimes block and cause time out. It's caused by the `a.py` process. `redis-cli monitor` shows that `a.py` process is trying to subscribe a very huge amount of celery-task-meta, like
`"SUBSCRIBE" "celery-task-meta-f6347dbe-c91b-4c95-bcbd-3dfefbcb2f46" "celery-task-meta-83f7be2a-2906-4e34-965a-47cec416d6df" "celery-task-meta-3c3e8eff-711d-4d44-bbd4-d36adea85ecd" "celery-task-meta-22492fff-2b7a-4e69-83de-71191e66861c" "celery-task-meta-1ae1f78a-ad78-47eb-a422-25d42a33fd83" "celery-task-meta-ed041055-f2cf-4f60-a531-dbc764dff5c4" ......`

I wander why it behaves like this, is it a bug or a normal act?

**Comment by gugu** [comment]
It is how celery 4 work – instead of get/set it subscribes on changes for tasks in chord, as fas as I know

**Comment by Eloahman** [comment]
@gugu I am curious that why does Celery do so. For example, when we use Celery in web for sending email, which I think it's a very common sense, the process which adds the task into the Celery does not exactly care about the result. So in Redis, maybe it should use `PUBLISH` instead of `SUBSCRIBE`?
I notice that after `SUBSCRIBE` performance, there will always be a `LPUSH` followed, I guess it's used to avoid multiple workers achieve the same task.
Oops, I'm now very curious about how Celery works. Do you have any idea or blog or something else?

**Comment by shidenggui** [comment]
celery:4.0.2 python:3.5.2 redis:3.2.1
os: CentOS release 6.7 (Final)
I also meet this problem. When I run celery some hours,It while be subscribe ten of thousands `celery-task-meta-xxx`.Sometimes it made task.get() raise `redis.exceptions.ResponseError: unknown command 'celery-task-meta-xxxx'` error.

**Comment by auvipy** [comment]
try the new release and docs and report the issue again

**Comment by wsYdd** [comment]
This new release is v4.2？
When do you plan to release this version?

**Comment by auvipy** [comment]
I will reopen if this can be reproduced in master. check the milestone only 1 documentation blocker remain

**Comment by VictorLeP** [comment]
I still notice a (slowly) ever-growing `SUBSCRIBE` command on master (using `redis-cli monitor`), when using RabbitMQ as broker and Redis as backend. (The sheer size of this command seems to eventually cause the `ResponseError` reported in https://github.com/celery/celery/issues/3808#issuecomment-288965295). So it seems this issue is still present.

Report:
```
software -> celery:4.2.0 (latentcall) kombu:4.1.0 py:3.6.3
            billiard:3.5.0.3 py-amqp:2.2.2
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://:**@**:6379/0
```

**Comment by georgepsarakis** [comment]
@VictorLeP there are some channel subscriptions opened by the worker (in case of chord or other workflows using results) and also by the client that waits for the task result. So, depending on the usage, and how many tasks you have simultaneously being executed, you may see a growing number of channels. Are you certain that this appears on `master`?

**Comment by VictorLeP** [comment]
@georgepsarakis Yes, I tested it with the latest `master` version (also tested with kombu's `master` version now). I use 'normal' tasks (sent using `app.send_task`), of which there is a constant stream to the workers, but I see in the worker logs that the tasks that appear in the growing subscription list have succeeded. In any case, there are appropriate timeouts and the task ID remain in the subscription list longer than the timeout.

**Comment by jetz** [comment]
Same issue. In my case, just a few calls like `somefunc.delay()`, produces millions of channels with about 33G memory used, my server is trembling :cry:, must we wait for v5.0?

**Comment by uday-rayala** [comment]
We are facing the same issue. Creating new tasks becomes really slow and when I checked the SLOWLOG, we found subscribe calls with huge number of channels are very slow. It looked like these subscribe calls are made from kombu and I get the big subscribe calls after the queue size reaches around ~300k. It might be because of Redis having a limitation on the number of subscribed channels.

Surprisingly, this happens even for tasks with `ignore_result=True` and not running a celery worker. I expected no subscribe calls made in this scenario. Then I found this [code](https://github.com/celery/celery/blob/master/celery/events/event.py#L58). I wonder if this reason for the subscribe calls. Can someone with more context about this help confirm?

**Comment by jackdbernier** [comment]
We are experiencing something similar.

We have long living processes that publish tasks (kafka consumers in our case). After a while, they start to slow down drastically.

I have started notice in the redis logs statements like this 
```
2396:M 07 Apr 16:00:52.970 # Client id=1222 addr=[::1]:60295 fd=6 name= age=2 idle=0 flags=N db=0 sub=293154 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1540 omem=34698932 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
2396:M 07 Apr 16:00:53.902 - Accepted ::1:60296
2396:M 07 Apr 16:00:56.042 # Client id=1223 addr=[::1]:60296 fd=6 name= age=2 idle=0 flags=N db=0 sub=293185 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1540 omem=34698932 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
2396:M 07 Apr 16:00:56.727 - Accepted ::1:60298
2396:M 07 Apr 16:00:58.781 # Client id=1224 addr=[::1]:60298 fd=6 name= age=2 idle=0 flags=N db=0 sub=293237 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1541 omem=34704604 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
2396:M 07 Apr 16:00:59.413 - Accepted ::1:60299
2396:M 07 Apr 16:01:00.539 - DB 0: 256808 keys (256795 volatile) in 262144 slots HT.
2396:M 07 Apr 16:01:00.539 - 5 clients connected (0 slaves), 2411690336 bytes in use
```
You can notice a connection after every output buffer limits reached.


It's my understanding that once the output buffer limit is reached, redis disconnects the client. This is when I think the python process publishing tasks then try to re-connect, and re-subscribe to all task ids it published up to that point.

In the redis slow logs, I get

```
10) 1) (integer) 1019
    2) (integer) 1523141684
    3) (integer) 617009
    4)  1) "SUBSCRIBE"
        2) "celery-task-meta-8b952b48-1f09-4592-b181-52bd356abd19"
        3) "celery-task-meta-cd5c8e64-9ddc-406b-93a5-0328a0cf03d9"
        4) "celery-task-meta-fc0c1afd-f362-4561-9b3f-ce25511e8c04"
        5) "celery-task-meta-d48dbeb4-7b83-4b0b-84a1-8a80715d0663"
        6) "celery-task-meta-ba82fe39-eb05-492c-bde6-1171b27b47ed"
        7) "celery-task-meta-dc129c56-24d0-49fc-90e2-3ad70dbf5610"
        8) "celery-task-meta-2fbd6cd4-c37b-4465-91cb-a2efe8d707ae"
        9) "celery-task-meta-38d859ee-47a2-472f-9650-b3a114fa03ee"
       10) "celery-task-meta-0a337213-c643-4b8a-8016-c71edcb289a9"
       11) "celery-task-meta-1ce17b04-6a3b-4419-8764-72da551db8a0"
       12) "celery-task-meta-e520485c-8596-47fc-a4f6-fe135e0d2e91"
       13) "celery-task-meta-a33a133a-5ea1-497a-9f9e-8b37c6224c70"
       14) "celery-task-meta-9deb582f-ad3f-403e-a401-27dd3c977701"
       15) "celery-task-meta-7f90469a-4bc7-4771-82ba-57c0c6de2465"
       16) "celery-task-meta-20530879-ddaa-4d87-894c-c4c13fe0d8a8"
       17) "celery-task-meta-103a2a45-0121-42a6-a961-a3e18648cbb2"
       18) "celery-task-meta-0d2ed52d-64eb-43db-b2b5-47a0ee76e563"
       19) "celery-task-meta-bc1237b7-9f41-4097-bb0c-e39080ca38d1"
       20) "celery-task-meta-344ef058-f85d-4a0f-a037-1d210fb12a7b"
       21) "celery-task-meta-d2a13c3c-69c4-4a93-b100-bfcbf08d7376"
       22) "celery-task-meta-60cb5163-a3f9-400b-8d6f-6d5eb1d29831"
       23) "celery-task-meta-a1bfb9db-9416-4d8d-ba05-607ca5f489e2"
       24) "celery-task-meta-75bb6e3b-079e-4579-8953-150681a6dd73"
       25) "celery-task-meta-fb742914-6481-437f-b36a-fbaa4dfdaf6a"
       26) "celery-task-meta-f780906f-9295-4d13-b2c4-807d01f3448d"
       27) "celery-task-meta-83eb2ae1-a8d6-4f60-9f03-f275df72dfde"
       28) "celery-task-meta-f9aead27-1640-48ce-b9bb-2722212ec41c"
       29) "celery-task-meta-10b93380-3788-4c16-955a-d40770b2a84e"
       30) "celery-task-meta-8a6995af-ab0c-4198-a7d4-8b12ad53b4d6"
       31) "celery-task-meta-43269a9a-530b-4bc0-8343-89b1811e4fcf"
       32) "... (287955 more arguments)"
```

where `       32) "... (287955 more arguments)"` is the number of tasks the process published up to that point.

You can also reproduce if you send `client kill` commands to force the python process to re-connect.

The only workaround the issue so far is to completely disable the backend result or use a sql database as a backend result.

Is there a way to limit the number of task ids the process subscribes to? Right now it looks like an unbounded list.

**Comment by auvipy** [comment]
you could check the patch of #3815 and if it fix the issue feel free to complete it so that it could be included in 4.2 release

**Comment by jackdbernier** [comment]
The redis library re-subscribe to any channels and patterns previously subscribed to
https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L2369
This explains the behavior. I'm still not exactly sure why celery does not unsubscribe. Though, I wonder what would happen if the worker is backed up or down.

I will check the patch.

**Comment by jackdbernier** [comment]
If I read the code properly, when ignore_result is True, then the result will never be stored in redis (expected). Therefore, the process submitting the task will never receive a message for the task id and the number of channels will just keep on growing for the entire lifecycle of the process (un-expected). This has a side-effect that if for any reasons, redis.py needs to reconnect, it will also re-subscribe to all task ids. This does not seem related to chords. Does it need a new bug?

Should apply_async/send_task not subscribe to the result if ignore_result is True? That seems to aggravate the problem here.

So far, I've found 3 cases where a process could start accumulating channels.
1) It is processing a burst of events, submitting more tasks than usual, and the workers are backing up.
2) the workers are down (intentionally or not)
3) ignore_result=True

Number 3 is by far the worst since it is normal scenario. Am I understanding this correctly? I understand the design decision to subscribe instead of polling. It makes a lot of sense. I'm wondering if number 3 is an oversight. I am still a bit worried about 1 and 2 but those could be claimed as normal limitations of redis as a result backend.

**Comment by chetandhembre** [comment]
Anyone find any work around here, until this is pushed in the new release.
We are facing this issue in production.

**Comment by jetz** [comment]
@chetandhembre In our scenario, we don't need result (`ignore_result=True`), so remove  config `result_backend='redis://password@127.0.0.1:6379` solve the problem temporarily. may be help?

**Comment by georgepsarakis** [comment]
@VictorLeP @jackdbernier @chetandhembre @jetz @uday-rayala we would really appreciate your feedback on the possible fix.

**Comment by jackdbernier** [comment]
How does it work if you ignore results for those tasks? In our setup, we store results for some tasks and ignore others.

Does it have to subscribe to the task before you explicitly request results? Are there some internal parts in celery that require the process that submits the task to receive events about that task? For what I understand, it is to avoid polling.

I.E

```
result = my_task.delay()    # <----- Currently, I think it subscribes here
result.get()    # <----- why not here? Not everyone gets to this point.
```

We also have cases where we ignore results except for errors.

**Comment by georgepsarakis** [comment]
@jackdbernier I understand your point, we might need to look further into this. Have you by any chance had a look at #4666 ? It might be solving the issue you are facing.

**Comment by jackdbernier** [comment]
I won't have time to test #4666 on my side for the next few weeks. Is it supposed to work with tasks where the result is ignored?

**Comment by georgepsarakis** [comment]
@jackdbernier please see this [PR](https://github.com/celery/celery/pull/4709) for ignored results.

**Comment by wsyzxcn** [comment]
> We are experiencing something similar.
> 
> We have long living processes that publish tasks (kafka consumers in our case). After a while, they start to slow down drastically.
> 
> I have started notice in the redis logs statements like this
> 
> ```
> 2396:M 07 Apr 16:00:52.970 # Client id=1222 addr=[::1]:60295 fd=6 name= age=2 idle=0 flags=N db=0 sub=293154 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1540 omem=34698932 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
> 2396:M 07 Apr 16:00:53.902 - Accepted ::1:60296
> 2396:M 07 Apr 16:00:56.042 # Client id=1223 addr=[::1]:60296 fd=6 name= age=2 idle=0 flags=N db=0 sub=293185 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1540 omem=34698932 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
> 2396:M 07 Apr 16:00:56.727 - Accepted ::1:60298
> 2396:M 07 Apr 16:00:58.781 # Client id=1224 addr=[::1]:60298 fd=6 name= age=2 idle=0 flags=N db=0 sub=293237 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=1541 omem=34704604 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
> 2396:M 07 Apr 16:00:59.413 - Accepted ::1:60299
> 2396:M 07 Apr 16:01:00.539 - DB 0: 256808 keys (256795 volatile) in 262144 slots HT.
> 2396:M 07 Apr 16:01:00.539 - 5 clients connected (0 slaves), 2411690336 bytes in use
> ```
> You can notice a connection after every output buffer limits reached.
> 
> It's my understanding that once the output buffer limit is reached, redis disconnects the client. This is when I think the python process publishing tasks then try to re-connect, and re-subscribe to all task ids it published up to that point.
> 
> In the redis slow logs, I get
> 
> ```
> 10) 1) (integer) 1019
>     2) (integer) 1523141684
>     3) (integer) 617009
>     4)  1) "SUBSCRIBE"
>         2) "celery-task-meta-8b952b48-1f09-4592-b181-52bd356abd19"
>         3) "celery-task-meta-cd5c8e64-9ddc-406b-93a5-0328a0cf03d9"
>         4) "celery-task-meta-fc0c1afd-f362-4561-9b3f-ce25511e8c04"
>         5) "celery-task-meta-d48dbeb4-7b83-4b0b-84a1-8a80715d0663"
>         6) "celery-task-meta-ba82fe39-eb05-492c-bde6-1171b27b47ed"
>         7) "celery-task-meta-dc129c56-24d0-49fc-90e2-3ad70dbf5610"
>         8) "celery-task-meta-2fbd6cd4-c37b-4465-91cb-a2efe8d707ae"
>         9) "celery-task-meta-38d859ee-47a2-472f-9650-b3a114fa03ee"
>        10) "celery-task-meta-0a337213-c643-4b8a-8016-c71edcb289a9"
>        11) "celery-task-meta-1ce17b04-6a3b-4419-8764-72da551db8a0"
>        12) "celery-task-meta-e520485c-8596-47fc-a4f6-fe135e0d2e91"
>        13) "celery-task-meta-a33a133a-5ea1-497a-9f9e-8b37c6224c70"
>        14) "celery-task-meta-9deb582f-ad3f-403e-a401-27dd3c977701"
>        15) "celery-task-meta-7f90469a-4bc7-4771-82ba-57c0c6de2465"
>        16) "celery-task-meta-20530879-ddaa-4d87-894c-c4c13fe0d8a8"
>        17) "celery-task-meta-103a2a45-0121-42a6-a961-a3e18648cbb2"
>        18) "celery-task-meta-0d2ed52d-64eb-43db-b2b5-47a0ee76e563"
>        19) "celery-task-meta-bc1237b7-9f41-4097-bb0c-e39080ca38d1"
>        20) "celery-task-meta-344ef058-f85d-4a0f-a037-1d210fb12a7b"
>        21) "celery-task-meta-d2a13c3c-69c4-4a93-b100-bfcbf08d7376"
>        22) "celery-task-meta-60cb5163-a3f9-400b-8d6f-6d5eb1d29831"
>        23) "celery-task-meta-a1bfb9db-9416-4d8d-ba05-607ca5f489e2"
>        24) "celery-task-meta-75bb6e3b-079e-4579-8953-150681a6dd73"
>        25) "celery-task-meta-fb742914-6481-437f-b36a-fbaa4dfdaf6a"
>        26) "celery-task-meta-f780906f-9295-4d13-b2c4-807d01f3448d"
>        27) "celery-task-meta-83eb2ae1-a8d6-4f60-9f03-f275df72dfde"
>        28) "celery-task-meta-f9aead27-1640-48ce-b9bb-2722212ec41c"
>        29) "celery-task-meta-10b93380-3788-4c16-955a-d40770b2a84e"
>        30) "celery-task-meta-8a6995af-ab0c-4198-a7d4-8b12ad53b4d6"
>        31) "celery-task-meta-43269a9a-530b-4bc0-8343-89b1811e4fcf"
>        32) "... (287955 more arguments)"
> ```
> where ` 32) "... (287955 more arguments)"` is the number of tasks the process published up to that point.
> 
> You can also reproduce if you send `client kill` commands to force the python process to re-connect.
> 
> The only workaround for the issue that I've found so far is to completely disable the backend result or use a sql database as a backend result.
> 
> Is there a way to limit the number of task ids the process subscribes to? Right now it looks like an unbounded list.
> 
> Version: 4.1.0 (latentcall)
> Redis server v=3.0.7
> 
> I will try with master. I have a small program to reproduce the issue locally.
> 
> Edit: I successfully reproduced using 4.2.0rc2
> 
> Is it related/similar to #3815?

celery version 4.2.1 still has this problem, I think your are right. I checked the log when celery task publisher subscribe large amount of channels, redis log print exceed output buffer limit lines of this client.
maybe redis-py lib's re-subscribe is not wise enough for celery. or maybe when re-connection we should let the web application aware of the re-connection, and let developer handle this situation themselves.

**Comment by WeipingGuo** [comment]
Which release do we expect the fix to be included? Thanks

**Comment by georgepsarakis** [comment]
@WeipingGuo should be fixed in the latest release, are you still observing this?

**Comment by WeipingGuo** [comment]
@georgepsarakis thanks, you means 4.2.1 or 4.3.0rc?

**Comment by neaket360pi** [comment]
@georgepsarakis 4.2.1 should have the fix.  I have not seen this issue appear again.

**Comment by charlescapps** [comment]
We are still seeing this issue in Celery 4.2.1, kombu 4.2.1, redis 2.10.6

**Comment by charlescapps** [comment]
Why was this closed? I can't find clearly in the comments where the fix may have occurred. #4666 doesn't fix it since that's included in 4.2.1 but the bug still occurs.

**Comment by thedrow** [comment]
@neaket360pi Reported this issue fixed.
We got no feedback on the fix from other users that confirmed this bug initially.

Are you sure it is exactly the same bug? Have you tried a later version?

**Comment by charlescapps** [comment]
> Are you sure it is exactly the same bug? Have you tried a later version?

It has the exact same symptoms. The top 1,000 commands listed by `SLOWLOG GET` in Redis are all `SUBSCRIBE` commands that are sending 300,000+ `celery-task-meta-...` keys. 

If I bounce our worker nodes then the `SUBSCRIBE` command immediately goes back to sending a very small number of keys and the incoming bytes to Redis drops from 12MB/s to 100KB/s. 

According to other users above, there were still issues in 4.2.1 and there could be multiple root causes. 

@wsyzxcn said:
> celery version 4.2.1 still has this problem, I think your are right. I checked the log when celery task publisher subscribe large amount of channels, redis log print exceed output buffer limit lines of this client.
> maybe redis-py lib's re-subscribe is not wise enough for celery. or maybe when re-connection we should let the web application aware of the re-connection, and let developer handle this situation themselves.

I'm going to try upgrading to Celery 4.3.0 and Redis 3.2.0. Definitely doesn't seem normal to have worker nodes DoS our Redis instance under low traffic!

**Comment by thedrow** [comment]
I'm reopening.
I'd appreciate if you investigated this further.
We're busy with making 5.0 happen and other PRs at the moment.

**Comment by georgepsarakis** [comment]
@charlescapps thanks for the feedback! Is the problem reproducible with the initial example in the description? Are you perhaps using some other workfrom from [Canvas](http://docs.celeryproject.org/en/latest/userguide/canvas.html)? It would be great if you could provide a minimal example for other contributors to reproduce the issue, as we can also build a test case around it!

**Comment by srinathganesh1** [comment]
any tips to re-create this issue?

**Comment by BrunoDesthuilliers** [comment]
I still have the issue here with 4.4.0, using [gugu's code](https://github.com/celery/celery/issues/3812) so it's quite easy to reproduce. 

celery  report:

```
software -> celery:4.4.0 (cliffs) kombu:4.6.7 py:2.7.17
            billiard:3.6.1.0 py-amqp:2.5.2
platform -> system:Linux arch:64bit
            kernel version:5.3.0-26-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:redis://localhost/

worker_max_tasks_per_child: 10
result_extended: True
worker_prefetch_multiplier: 1
worker_send_sent_event: True
result_expires: 86400
worker_disable_rate_limits: True
worker_send_task_events: True
timezone: u'Europe/Paris'
track_started: True
broker_url: u'amqp://guest:********@localhost:5672//'
result_backend: u'redis://localhost/'
worker_pool_restarts: True

```

**Comment by BrunoDesthuilliers** [comment]
The celery worker, redis-cli monitor and redis-cli pub-sub results here [issue.log](https://github.com/celery/celery/files/4128938/issue.log)

On can see that for the first `add` task:

`[2020-01-29 15:43:40,079: INFO/MainProcess] Received task: app.add[ebd87d2c-4e63-413b-a931-46c37557a8ae] 
`

Redis gets a first subscribe, a unsubscribe, then two subscribes again and no unsubscribe:

```
$ ag "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae" issue.log

3:1) "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae"
14:1580309020.066143 [0 127.0.0.1:57600] "SUBSCRIBE" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae"
16:1580309020.078931 [0 127.0.0.1:57600] "UNSUBSCRIBE" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae"
17:1580309020.078998 [0 127.0.0.1:57600] "SUBSCRIBE" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae"
25:1580309020.081221 [0 127.0.0.1:57594] "SUBSCRIBE" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae"
30:1580309025.093896 [0 127.0.0.1:57610] "SETEX" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae" "86400" "{\"status\": \"SUCCESS\", \"retries\": 0, \"args\": [5, 6], \"name\": \"app.add\", \"date_done\": \"2020-01-29T14:43:45.086982\", \"task_id\": \"ebd87d2c-4e63-413b-a931-46c37557a8ae\", \"traceback\": null, \"worker\": \"celery@blookup-MS-7982\", \"queue\": \"celery\", \"parent_id\": \"fb465e22-52a8-4eb7-b954-5d4935fc14f6\", \"result\": 11, \"kwargs\": {}, \"group_id\": \"26336a79-5060-45b2-962e-18424911bac7\", \"children\": []}"
31:1580309025.093954 [0 127.0.0.1:57610] "PUBLISH" "celery-task-meta-ebd87d2c-4e63-413b-a931-46c37557a8ae" "{\"status\": \"SUCCESS\", \"retries\": 0, \"args\": [5, 6], \"name\": \"app.add\", \"date_done\": \"2020-01-29T14:43:45.086982\", \"task_id\": \"ebd87d2c-4e63-413b-a931-46c37557a8ae\", \"traceback\": null, \"worker\": \"celery@blookup-MS-7982\", \"queue\": \"celery\", \"parent_id\": \"fb465e22-52a8-4eb7-b954-5d4935fc14f6\", \"result\": 11, \"kwargs\": {}, \"group_id\": \"26336a79-5060-45b2-962e-18424911bac7\", \"children\": []}"

```

**Comment by WeipingGuo** [comment]
Anybody has workaround for this? I set up the `result_expires` to 10 min and thinking to reduce further

100) 1) (integer) 962195
     2) (integer) 1639932515
     3) (integer) 1010686
     4)  1) "SUBSCRIBE"
         2) "celery-task-meta-92eac210-169a-4e6e-9b18-c5cd2137ad6f"
         3) "celery-task-meta-2a6f79b0-2789-4534-a78c-0998b8a37b70"
         4) "celery-task-meta-c43de8db-01af-44d3-8038-9bcfc1755aea"
         5) "celery-task-meta-db3fa50f-0675-44a2-86ea-f61d77b0fa46"
         6) "celery-task-meta-d2c76f51-7c22-4be9-810f-c3795d0324e1"
        ...     
        32) "... (509970 more arguments)"

**Comment by WeipingGuo** [comment]
Same question, we are upgrading from celery 4 to 5, hope this is fixed. Thanks

**Comment by gaozhidf** [comment]
> Same question, we are upgrading from celery 4 to 5, hope this is fixed. We see the same issue for redis==3.5.3 and celery==4.4.0
> 
> ```
> 9) 1) (integer) 470046
>     2) (integer) 1682982915
>     3) (integer) 759268
>     4)  1) "SUBSCRIBE"
>         2) "celery-task-meta-28ca8a3e-c4e7-4be9-95bb-362d6947ddcb"
>         3) "celery-task-meta-8f698cbb-4d78-49c3-8292-5342a3484d21"
>         4) "celery-task-meta-7621a230-3ccb-424d-92dc-e5cec8dc0011"
>         5) "celery-task-meta-4e898b69-7602-42e3-8aa1-8008540e0830"
> ```

do you fix this after upgrading to celery 5?

**Comment by WeipingGuo** [comment]
@gaozhidf  We have not completed the full upgrade yet, fingers crossed
