### ISSUE TITLE
Worker crash when providing un-un-pickleable Exception to retry arg

### ISSUE THREAD

**Issue by amcgavin** [celery/celery#6990]
# Checklist

* [x] I have verified that the issue exists against the `master` branch of Celery.
* [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
* [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
* [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information
* [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
* [x] I have verified that the issue exists against the `master` branch of Celery.
* [x] I have included the contents of ``pip freeze`` in the issue.
* [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

* [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
* [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
* [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
* [ ] I have tried reproducing the issue on more than one operating system.
* [ ] I have tried reproducing the issue on more than one workers pool.
* [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
* [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues
* None

#### Possible Duplicates
* None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b>
</summary>
<p>

```

software -> celery:5.2.0rc1 (dawn-chorus) kombu:5.2.0rc1 py:3.7.12
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit, ELF
            kernel version:5.10.47-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:disabled

broker_url: 'amqp://guest:********@broker:5672//'
deprecated_settings: None

```

</p>
</details>

# Steps to Reproduce
## Required Dependencies

* **Minimal Python Version**: 3.7
* **Minimal Celery Version**: 5.1.2
* **Minimal Kombu Version**: N/A
* **Minimal Broker Version**: N/A
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: N/A
* **Minimal Broker Client Version**: N/A
* **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.0.6
billiard==3.6.4.0
cached-property==1.5.2
celery @ git+https://github.com/celery/celery@49452916f94d5ec60af246cea600855e6d976b48
click==8.0.1
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
importlib-metadata==4.8.1
kombu==5.2.0rc1
prompt-toolkit==3.0.20
pytz==2021.3
six==1.16.0
typing-extensions==3.10.0.2
vine==5.0.0
wcwidth==0.2.5
zipp==3.6.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
from celery import Celery

app = Celery("tasks", broker="pyamqp://guest@broker//")


class BrokenException(Exception):
    """
    This Exception can't be unpickled by default
    """
    def __init__(self, msg, other_arg):
        super().__init__(msg)
        self.other_arg = other_arg

@app.task(bind=True)
def unsafe_exception(self):
    self.retry(exc=BrokenException("msg", "other_arg"))


def main():
    unsafe_exception.delay()

if __name__ == "__main__":
    main()
```

Then run with `python tasks.py`

Repo here:
https://github.com/amcgavin/celery-issue/
</p>
</details>

# Expected Behavior
Exception occurs in the worker handler, but handled gracefully.

_note_: this was the behaviour in celery==5.0.2

# Actual Behavior
worker process crashes, with exit code 0.

Note that raising the exception directly doesn't crash (see the repo for detailed example).

```
celery_1  | [2021-10-08 08:34:10,200: INFO/MainProcess] Task tasks.unsafe_exception[38b08c18-451b-4645-a4ac-ada2e6b43e5e] received
celery_1  | [2021-10-08 08:34:10,201: CRITICAL/MainProcess] Unrecoverable error: TypeError("__init__() missing 1 required positional argument: 'other_arg'")
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
celery_1  |     c.loop(*c.loop_args())
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
celery_1  |     next(loop)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
celery_1  |     cb(*cbargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
celery_1  |     next(it)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
celery_1  |     message = load(bufv)
celery_1  | TypeError: __init__() missing 1 required positional argument: 'other_arg'
celery_1  | [2021-10-08 08:34:41,378: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0 Job: 2.')
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
celery_1  |     c.loop(*c.loop_args())
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
celery_1  |     next(loop)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
celery_1  |     cb(*cbargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
celery_1  |     next(it)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
celery_1  |     message = load(bufv)
celery_1  | TypeError: __init__() missing 1 required positional argument: 'other_arg'
celery_1  | 
celery_1  | During handling of the above exception, another exception occurred:
celery_1  | 
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celery_1  |     human_status(exitcode), job._job),
celery_1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0 Job: 2.
celery-example_celery_1 exited with code 0
```

**Comment by auvipy** [comment]
Unrecoverable error: TypeError("__init__() missing 1 required positional argument: 'other_arg'")
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
celery_1  |     c.loop(*c.loop_args())
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
celery_1  |     next(loop)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
celery_1  |     cb(*cbargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
celery_1  |     next(it)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
celery_1  |     message = load(bufv)
celery_1  | TypeError: __init__() missing 1 required positional argument: 'other_arg'
celery_1  | [2021-10-08 08:34:41,378: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0 Job: 2.')
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
celery_1  |     c.loop(*c.loop_args())
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 81, in asynloop
celery_1  |     next(loop)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
celery_1  |     cb(*cbargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
celery_1  |     next(it)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
celery_1  |     message = load(bufv)
celery_1  | TypeError: __init__() missing 1 required positional argument: 'other_arg'
celery_1  | 
celery_1  | During handling of the above exception, another exception occurred:
celery_1  | 
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
celery_1  |     human_status(exitcode), job._job),
celery_1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 0 Job: 2.
celery-example_celery_1 exited with code 0

@amcgavin amcgavin added the Issue Type: Bug Report label yesterday
@open-collective-bot
open-collective-bot bot commented yesterday

Hey @amcgavin wave,
Thank you for opening an issue. We will get back to you as soon as we can.
Also, check out our Open Collective and consider backing us - every little helps!

We also offer priority support for our sponsors.
If you require immediate assistance please consider sponsoring us.
@auvipy
Member
auvipy commented now

could you please try celery 5.2.0rc1?
@auvipy
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow its contributing guidelines.
Show your support for celery by sponsoring them.
Assignees
No one—
Labels
Issue Type: Bug Report
Projects
None yet
Milestone
No milestone
Linked pull requests

Successfully merging a pull request may close this issue.
None yet
Notifications
Customize

You’re receiving notifications because you’re watching this repository.
2 participants
@amcgavin
@auvipy
Delete issue

**Comment by amcgavin** [comment]
No problem, thanks for looking!

**Comment by violuke** [comment]
We're getting this issue on 5.2.3 (latest at time of writing). We're going to swap to pass these as positional args (instead of kwargs) and see if this helps. We're not failing to pass them in our own code, and does seem to be caused by the retry in Celery and the stack trace we get matches this and also https://github.com/celery/celery/discussions/7226

**Comment by auvipy** [comment]
any one up for contribution?

**Comment by georgemessiha22** [comment]
We are also facing the same exact bug on version5.1.2

It happens only for the tasks with retry, when an exception is raised to do the retry.

Note: it does not happen every time.

**Comment by thiagosalvatore** [comment]
I was able to reproduce it and found exactly what is causing the problem.

If you create and raise an exception like this inside your celery task, things are going to break:
```python
class MyException(Exception):
    def __init__(self, msg, another_arg):
        super().__init__(msg)
        self.another_arg = another_arg
```

The reason for that is because the `Exception` implements a few methods that pickle uses behind the scenes. If the exception is defined like below, things are going to work fine:

```python
class MyException(Exception):
    def __init__(self, msg, another_arg):
        super().__init__(msg, another_arg)
        self.another_arg = another_arg
```

I wasn't able to find a way to open a fix for that, but in my code I fixed the issues by doing this and creating an intermediate exception for unhandled things that are not following this pattern

**Comment by MusHusKat** [comment]
Is there a way temporarily fix this? In our application, the worker crashing is quite painful.

**Comment by jarcoal** [comment]
Confirming that this is still an issue in 5.2.6.

My organization encountered this issue due to the `InvalidRequestError` exception in the `stripe` package.  Going to add this so that anyone with the same issue might find this thread:

```
TypeError: __init__() missing 1 required positional argument: 'param'
```

**Comment by mdineen** [comment]
5.2.6 as well. We encounter it in mailchimp_transactional.

```
TypeError: __init__() missing 2 required positional arguments: 'text' and 'status_code'
```

**Comment by fjsj** [comment]
Sadly, @thiagosalvatore solution didn't work for me. My exception is not pickleable and Celery breaks due to that.
This is a Python issue: https://github.com/python/cpython/issues/87626
But Celery could handle this more gracefully, perhaps? Not sure.

For others who are facing this: don't let your custom exceptions be thrown inside Celery tasks, but if you really need that, you need to make your custom exception pickleable by implementing `__reduce__`. See: https://github.com/python/cpython/issues/101159#issuecomment-1398018001

**Comment by auvipy** [comment]
> But Celery could handle this more gracefully, perhaps? Not sure.

can you please give it a try and dig a bit deeper if you can come with something?

**Comment by fjsj** [comment]
@auvipy in general, what should be done if `_recv_message` throws an exception? Should the task be marked as failed? This means the task finished, but the result is not readable by Celery (either due to pickling error, like it's happening here, or due to some other error). What Celery should do in this case? I guess something better than breaking with worker crash, but I'm not sure what.

**Comment by auvipy** [comment]
we might raise / catch exception instead?

**Comment by fjsj** [comment]
I guess only a warning is doable at `_recv_message` level?
This exception happens at `ResultHandler`: https://github.com/celery/celery/blob/cb83eafe59782963cb0254edce23f485f03bfbf1/celery/concurrency/asynpool.py#L306

**Comment by Photonios** [comment]
The regression was introduced in Celery v5.0.2b2 in this commit: https://github.com/celery/celery/commit/b0326ab0e249288e8e551e78fcb88ab2c2b84bcb#diff-8895f024b21b48a064a12e678dab0fe1bb60a5af82b3b0273dc24ec94df2ad16R183

`self.excs` is a string (exception message), while `self.exc` is the exception passed to `Task.retry`. As a result, exceptions passed to `Task.retry` have to be pickable.

**Comment by auvipy** [comment]
can you please contribute a fix?

**Comment by fjsj** [comment]
I'm not able to contribute now, sorry. I'll remain watching this and may contribute with a solution in the next couple of months.

**Comment by Photonios** [comment]
> can you please contribute a fix?

I am not sure how this is supposed to be fixed. Reverting the commit that introduced the breaking change would re-open #6748. Some complicated hack with wrapping the exception might work, but my knowledge of Celery's code base is too limited to safely make such a change.

**Comment by youtux** [comment]
if it can help, the [fix I posted here](https://github.com/celery/celery/issues/6185#issuecomment-1458374393) worked for me, maybe we can modify celery following that.

**Comment by danihodovic** [comment]
I was able to reproduce this with celery==5.2.7.

I ran a Django shell that triggered a task and a Docker container that received and executed it. The broker is Redis.

```python
from celery import current_app as app


class MyCustomException(Exception):
    def __init__(self, message, extra_arg):
        super().__init__(message)
        self.extra_arg = extra_arg


@app.task(bind=True, max_retries=3)
def test_bubbles_up_exceptions(self):
    try:
        raise MyCustomException("message", "extra_arg")
    except Exception as ex:
        self.retry(exc=ex)
```

Simply running ./manage.py shell_plus with
```python
test_bubbles_up_exceptions.delay()
```

Results in this:

```
 INFO 2023-06-16 12:57:57,687 /usr/local/lib/python3.10/site-packages/celery/app/trace.py:131 {trace:info} ||| Task wario.delivery.celery.test_bubbles_up_exceptions[bf0ceb3b-b396-482d-b895-047a7bb063f8] retry: Retry in 180s: MyCustomException('message')
 CRITICAL 2023-06-16 12:57:57,687 /usr/local/lib/python3.10/site-packages/celery/worker/worker.py:207 {worker:start} ||| Unrecoverable error: TypeError("MyCustomException.__init__() missing 1 required positional argument: 'extra_arg'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 325, in on_result_readable
    next(it)
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 306, in _recv_message
    message = load(bufv)
TypeError: MyCustomException.__init__() missing 1 required positional argument: 'extra_arg'
```

**Comment by danihodovic** [comment]
I could not reproduce the error with celery==5.3.0. Thank you Celery development team. You are great.

```
 INFO 2023-06-16 13:02:57,751 /usr/local/lib/python3.10/site-packages/celery/worker/strategy.py:161 {strategy:task_message_handler} ||| Task wario.delivery.celery.test_bubbles_up_exceptions[4ea379be-dc57-4762-a755-8e5ac82ff520] received
 INFO 2023-06-16 13:02:57,755 /usr/local/lib/python3.10/site-packages/celery/app/trace.py:131 {trace:info} ||| Task wario.delivery.celery.test_bubbles_up_exceptions[4ea379be-dc57-4762-a755-8e5ac82ff520] retry: Retry in 180s: MyCustomException('message')
```

**Comment by auvipy** [comment]
> I could not reproduce the error with celery==5.3.0. Thank you Celery development team. You are great.
> 
> ```
>  INFO 2023-06-16 13:02:57,751 /usr/local/lib/python3.10/site-packages/celery/worker/strategy.py:161 {strategy:task_message_handler} ||| Task wario.delivery.celery.test_bubbles_up_exceptions[4ea379be-dc57-4762-a755-8e5ac82ff520] received
>  INFO 2023-06-16 13:02:57,755 /usr/local/lib/python3.10/site-packages/celery/app/trace.py:131 {trace:info} ||| Task wario.delivery.celery.test_bubbles_up_exceptions[4ea379be-dc57-4762-a755-8e5ac82ff520] retry: Retry in 180s: MyCustomException('message')
> ```

thank you
