### ISSUE TITLE
Celery Import Error

### ISSUE THREAD

**Issue by marimuthuei** [celery/celery#7783]
Not able to import Celery module when creating simple app.

from celery import Celery
ImportError: cannot import name 'Celery' from 'celery'

Additonal info:
This issue doesn't occur when we downgrade importlib-metadata to 4.12.0
Env details
![image](https://user-images.githubusercontent.com/55486262/193540909-f96e4503-44cf-45ed-b151-79af2cc6e12c.png)

**Comment by woutdenolf** [comment]
What python version? Seems to occur only with python 3.7 #7784

**Comment by woutdenolf** [comment]
Ok I guess because `importlib-metadata` is not installed when you install celery in a python 3.8 environment.

**Comment by ppanero** [comment]
similar imports are failing (e.g. `current_app`) with the same behavior (works when downgrading `importlib-metadata`). Seems to only be in python 3.7.

Tests with py3.8 **and** importlib-metadata works for me.

**Comment by marimuthuei** [comment]
its python3.7 env

**Comment by woutdenolf** [comment]
This seems to be the cause: https://github.com/python/importlib_metadata/pull/405

```python
Successfully installed importlib_metadata-4.13.0
$ python
Python 3.7.9 (default, Jul  5 2021, 22:17:33) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib_metadata import entry_points
>>> entry_points().get("celery.result_backends", list())
__main__:1: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
[]
```

So I guess we should fix

https://github.com/celery/celery/blob/59263b0409e3f02dc16ca8a3bd1e42b5a3eba36d/celery/utils/imports.py#L142-L145

**Comment by woutdenolf** [comment]
The kombu package probably has the same problem

https://github.com/celery/kombu/blob/97e887605b21a110e0ec304913930a8115987c6a/kombu/utils/compat.py#L93

**Comment by woutdenolf** [comment]
Made a fix for celery (https://github.com/celery/celery/pull/7785) and kombu (https://github.com/celery/kombu/pull/1601).

**Comment by woutdenolf** [comment]
This is also a solution: https://github.com/celery/celery/pull/7782

**Comment by marimuthuei** [comment]
@auvipy Can this issue will be resolved in celery ==4.4.7 version?

**Comment by auvipy** [comment]
nope

**Comment by jaraco** [comment]
> @auvipy Can this issue will be resolved in celery ==4.4.7 version?

As mentioned above, pinning to `importlib_metadata < 5` in your environment should work around the issue while keeping `celery == 4.4.7`.

**Comment by Nusnus** [comment]
Hey guys, the PR associated with this issue introduced a bug and the documentation cannot be built.
Relevant commit: https://github.com/celery/celery/pull/7785/commits/f77e98ae3ea5f970ec9c0f8787cba48bd5a2e443
Doc build error from this PR: https://readthedocs.org/projects/celery/builds/18287948/

Please revert until a proper fix is available, we cannot have breaking code in `master`.
@woutdenolf @auvipy

**Comment by auvipy** [comment]
Hey nusnus, the actual PR was squashed merged https://github.com/celery/celery/commit/a4545dbd549c7666bec561376ec75e484da8b475 , the commit you are refering should have the fix with the commit merged https://github.com/celery/celery/commit/a4545dbd549c7666bec561376ec75e484da8b475 . but if it still have the element of failure, we will revert to fix it.

**Comment by woutdenolf** [comment]
https://readthedocs.org/projects/celery/builds/18287948/

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/celery/envs/7785/lib/python3.7/site-packages/kombu/utils/compat.py", line 82, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

But we capture AttributeError

```
try:
    _entry_points = entry_points().get(namespace, [])
except AttributeError:
    _entry_points = entry_points().select(group=namespace)
```

So maybe you're looking at an old CI run?

**Comment by auvipy** [comment]
> https://readthedocs.org/projects/celery/builds/18287948/
> 
> ```
>   File "/home/docs/checkouts/readthedocs.org/user_builds/celery/envs/7785/lib/python3.7/site-packages/kombu/utils/compat.py", line 82, in entrypoints
>     for ep in importlib_metadata.entry_points().get(namespace, [])
> AttributeError: 'EntryPoints' object has no attribute 'get'
> ```
> 
> But we capture AttributeError
> 
> ```
> try:
>     _entry_points = entry_points().get(namespace, [])
> except AttributeError:
>     _entry_points = entry_points().select(group=namespace)
> ```
> 
> So maybe you're looking at an old CI run?

i have opened a revert pr, there the doc build is still failing, can you cross check please?

**Comment by woutdenolf** [comment]
Ah wait:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/celery/envs/7785/lib/python3.7/site-packages/kombu/utils/compat.py", line 82, in entrypoints
    for ep in importlib_metadata.entry_points().get(namespace, [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

This is an error from kombu. So it won't pass until we release kombu (fixed in https://github.com/celery/kombu/pull/1601).

**Comment by auvipy** [comment]
oh i see! a new beta of kombu should be released, I will do that

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/7834 testing

**Comment by woutdenolf** [comment]
Apart from kombu, it seems readthedocs was not using `requirements/docs.txt`. This works: https://github.com/celery/celery/pull/7835

**Comment by Nusnus** [comment]
Thank you @woutdenolf for investigating this and coming up with a solution **quickly**! Appreciate it. Hope it will get merged soon :)

**Comment by titusfx** [comment]
@jaraco downgrading importlib_metadata didn't work for me :(
